name: gms_alerts
description: Lightweight Granny Murray portal app with native school alerts.
publish_to: 'none'
version: 1.1.0+2

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  webview_flutter: ^4.10.0
  flutter_local_notifications: ^17.2.2
  permission_handler: ^11.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
